<?php

namespace App\Database\Seeds;

class ModuleSeeder extends \CodeIgniter\Database\Seeder
{
    public function run()
    {
        $data = [
            ['name' => 'Sistemas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Seguridad', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Presidencia', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Vivienda', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Serlav', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Ctas Ctes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Recuperaciones', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Segur Reindexa', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Segur Copia de Datos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Segur Restaurar Datos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Segur Usuarios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Segur Tablas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Pres Ingresos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Pres Consultas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Pres Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Pres Ing Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Pres Rep Por Orden Alfabe', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Pres Rep Padron General S', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Maestro', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Movimientos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Consultas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Mae Conceptos de Desc', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Mae Transf a Contab', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Mov Ingreso de Cobran', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Mov Emision de Recibo', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Mov Regularizacion Re', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Mov Descuentos Indebi', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Pre Con Res Ingr Cod Desc', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Rep Res Ing x Dia', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Con Plan de Cuentas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Con Códigos Auxiliar', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Con Fichas de Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist Caja Con Estados de Ctas C', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Con-Tabla Tipo Cambio', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Con-Monto Ingreso x B', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Con-Resumen de Ingr/E', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Rep-Detalle de Ing Di', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Rep-Resu Ing DiarxCod', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Rep-Resu Ing x Cta Co', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Rep-Pendientes regula', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Rep-Gastos x Centros', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pre-Con-Res Ing x Día', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Rep-Descuentos Indebi', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Rep-Regularizacion Re', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Compras', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Planillas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pre-Con-Resum Ingr/Egreso', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Mae-Tra-Ing de Caja', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Mae-Tra-Egr de Caja', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Mae-Tra-Regularizac', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pres-Rep-Aportes Efectuad', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Mae-Tra-Egr-Vale Defi', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Mae-Tra-Egr-Desc Inde', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Con-Centros de Costos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Con-Tabla Documentos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Segur-Cambio Fecha Proceso', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pre-Con-Ficha Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pre-Con-Res Ingr Prog Viv', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Proceso', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Maestro', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Movimientos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Consultas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Mae-Vivienda', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Mae-Titulación', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Mae-Tabla Feriados', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Mae-Coeficientes Int.', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Mov-Letras', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Mov-Aportaciones Viv.', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Mov-Bolsa Vipolina', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Con-Ficha Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Con-Prog c/s Título', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Con-Prog Tram seg min', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Con-Prog seg tipo Reg', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Con-Resum Prop x Prog', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Rep-Por Orden Alfábet', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Rep-Por Programa', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Rep-Padrón Gral SocxP', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Rep-Pagos de Viv Deta', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Rep-Resúm PagosxProgr', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Rep-Bolsa Vipolina', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Rep-Dsctos Efectuados', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Rep-Estados de Letras', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Maestros', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Movimientos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Consultas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Mae-Fichas Préstamos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Mae-Nuevos Préstamos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Mov-Cancelac. Préstam', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Mov-Eliminar Morosida', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Con-Pagos desde Caja', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Con-PC-Seguro Falleci', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Con-PC-Préstamos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Con-PC-Fondo Serlav', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Con-Fichas de Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Con-Garantes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Con-Estado Ctas Ctes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Con-Estado Cta Cte', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pre-Con-Res Título Propie', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-Por Orden Alfabét', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-Socios Dscts Inde', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-Socios Morosos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-Desctos Efectuado', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-Acum Mens de Caja', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-AC-Seguro Falleci', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-AC-Préstamos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-AC-Fondo Serlav', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Rep-Garantes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Maestros', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Consultas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Orden de Pago', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Mae-PagosxContab', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Mae-Aportaciones Vivi', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Con-Ficha de Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Electoral', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Mae-Actualiz. Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Maestros', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Ord-Estado Cta Cte', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Ord-Orden de Pago', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Ord-Orden de Pago Esp', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Mov-Pagos Aportes Ext', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Rep-Pagos AcuxCod Dst', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Rep-Pagos Acum. Socio', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Mae-Archivo Control', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Maestros', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Movimientos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Procesos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Soporte', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mae-Personal', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mae-Conceptos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mae-AFPs', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mae-Concep AFPs', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mae-Formulas Concepto', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mae-Patrón Fórmulas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mae-Situación Laboral', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mae-Cuentas Asto Cont', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mov-Concept Fijos/Var', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mov-Registro Horas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mov-Adelanto Quincena', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Mov-Cuenta Corriente', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Pro-Cálculo Planilla', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Pro-Cierre Periodo', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Pro-Transf. Vacacione', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Pro-Transf. Gratifica', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Pro-Transf. Contabili', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Pro-TC-Normal/Gratifi', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Pro-TC-Vacaciones', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Mvto Plan. Calcul', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Pre Plan. Calcula', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Boleta de Pagos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Resúmen x Concept', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Recibo Adelanto', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Libro Planilla', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Declar Jurad IPSS', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Aportes Prev AFPs', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Asiento Contable', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Sop-Estado de Persona', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Sop-Selec Proceso', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Sop-Selec Per. Calcul', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Sop-Genera Períodos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Sop-Periodos Transfer', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-Dcto Cta CtexPer', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Pla-Rep-ConceptoxPersonal', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Cta-Ord-Dcto Programado', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Ser-Mae-PagosxContabilida', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Caj-Con-RecibosxActualiza', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Movimientos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Mov-Notificaciones', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Mov-Pagos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Consultas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Con-Ficha de Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Con-Estado Cta Cte', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Con-Ordenes de Pago', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Rep-Notif x Programa', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Rep-DeudasxApoyProgVi', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Rep-Saldos PendxProg', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Rep-Pagos PendxFecVen', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Rec-Rep-Impr Notificacio', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Sist-Viv-Con-Orden de Pago', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco. Maestros', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Bancos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Tipo Mvto.Bancos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Movimientos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Cheques Vouchers', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Actu.Est.Cheque', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Mvto.Bancario', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Extracto Bancario', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Cheques Pendientes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Consultas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Por Banco', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Numero de Cuenta', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Referencia', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Por Día', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Saldo de Bancos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Plan de Cuentas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Codigo Auxiliar', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.centros de Costos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Dctos de Referencia', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Tipo de cambio', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Cheques Girados', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Flujo Diario', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco. Libro Bancos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Cheques pendientes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Procesos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Cambio Fecha', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco. Transferencia Contable', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Cierre Anual', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Bco.Ficha de Socio', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Cta. Voucher por Socio', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ser. Voucher por Socio', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Maestros', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Materiales', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Proveedores', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Activos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Distribución de Activos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Movimientos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Mvtos.Artículos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Procesos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Actualiza Saldos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Cierre fin Año', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Trans.Saldos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Transf.Contable', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Kardex cantidades', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.kardex Valorizado', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Consumo Artículos por Area', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Compras por Proveedor', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Saldo mes Actual', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Saldo mes anterior', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Alerta de Stock', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Toma de Inventario', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Registro de Inventario', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Soporte', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Alm.Fecha de Proceso', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ban.Rep.ctas.Contable', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ban.Rep.Estado de Cheque', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ban. Asientos anexos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ban.Genera Asientos Anexos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele.Movimientos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele.Ingresos por Multas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele.Consultas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele.Ficha de Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele.Estado de Cta.Cte.', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele. Reportes', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele.Socios afectos a Multas', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele.Padrón Socios', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele. Procesos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele. Cambio de Fecha', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ele. Transfe. a descto.Viviend', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Viv.Rep.Socios x Inst.Programa', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Viv.Archivo Documentos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Vir.Rep.Archivo de Documentos', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ban.Maestro Parte diario', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ban.Genera Parte Diario', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Ban. Voucher por Socio', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Viv.Documentos Personales', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Viv.Rep.Doctos. Personales', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Viv.Socios xProg.F.Pago', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Viv.Condición de Titulo', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Rec.Resum.Ing.Mens.xDíaxProp.V', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
            ['name' => 'Cta.Acumulado Apertura', 'icons' => '', 'module_id' => null, 'module_group_id' => 1],
        ];

        // Simple Queries
        //$this->db->query( "INSERT INTO groups_module (name) VALUES(:name)",  $data );

        // Using Query Builder
        $this->db->table('modules')->insertBatch($data);
    }
}
